### PR TITLE
Updated project to Angular 11

### PR DESCRIPTION
**Pull request by bujoralexandru**

### CODE REVIEW

**Comment by henryruhs** [comment]
@bujoralexandru I successfully tested your fixed version with Angular 11 but had to remove `@Required` from `TreetableComponent<T>` ... not sure what is going on but it has been reported here: https://github.com/mlrv/ng-material-treetable/issues/53

@mlrv Could you please merge this PR and remove `@Required` to release a working version on npmjs?

---

I released a temporary package for those who can't wait:

package.json:
```
"ng-material-treetable-next": "0.5.6-by-bujor-alexandru"
```

app.module.ts:
```
import { TreetableModule } from 'ng-material-treetable-next';
```

**Comment by wilding96** [comment]
This is really useful, thank you! And if the editor has an error, you can try to upgrade the editor angular plug-in to more than 10.

**Comment by ericlee1974** [comment]
Thanks for this - I also came across a problem with the call to the uuid in this and the main branch.

I changed the code as follows to get it working.

const uuidv4 = require('uuid');

    /**
     * Clone a Node<T> object and convert it to a SearchableNode<T>
     * @param tree the node to be converted
     */
    toSearchableTree(tree) {
        const treeClone = cloneDeep(tree);
        this.treeService.traverse(treeClone, (node) => {
            node.id = node.id ? node.id : uuidv4.v4();
        });

**Comment by freedev** [comment]
May I ask why this pull request is not merged?

**Comment by bujoralexandru** [comment]
I think that @mlrv is no longer active on this project, so this repo is kind of stuck in time. Best bet is to use the package mentioned by @henryruhs

**Comment by nicoesiea** [comment]
Question: I'm trying to use this lib on Angular 13 but I'm facing this issue:

> ./node_modules/ng-material-treetable-next/__ivy_ngcc__/fesm2015/ng-material-treetable-next.js:348:13-31 - Error: Module not found: Error: Package path ./v4 is not exported from package

Does someone can help me?
Thank you in advance

**Comment by henryruhs** [comment]
Just don't use software that is not maintained. Last commits are 3 years old... there is no reason to stick to this.

Fun fact: I did not even remember creating this patch release on NPM... :-)

**Comment by nicoesiea** [comment]
True, but is there another one?

**Comment by nicoesiea** [comment]
I replace it with another lib ;)

**Comment by annamichalik** [comment]
> Could you advice the library which I should use in Angular 14 ? I have updated a project from Angular 9 and I am looking for the best alternative

**Pull request closed without merging**
